/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatsappIndexRouteImport } from './routes/whatsapp.index'
import { Route as WhatsappTemplatesRouteImport } from './routes/whatsapp.templates'
import { Route as WhatsappLogsRouteImport } from './routes/whatsapp.logs'
import { Route as WhatsappCampaignsRouteImport } from './routes/whatsapp.campaigns'
import { Route as WhatsappAutomationRouteImport } from './routes/whatsapp.automation'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappIndexRoute = WhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappTemplatesRoute = WhatsappTemplatesRouteImport.update({
  id: '/whatsapp/templates',
  path: '/whatsapp/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappLogsRoute = WhatsappLogsRouteImport.update({
  id: '/whatsapp/logs',
  path: '/whatsapp/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappCampaignsRoute = WhatsappCampaignsRouteImport.update({
  id: '/whatsapp/campaigns',
  path: '/whatsapp/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappAutomationRoute = WhatsappAutomationRouteImport.update({
  id: '/whatsapp/automation',
  path: '/whatsapp/automation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/clients': typeof ClientsRoute
  '/inventory': typeof InventoryRoute
  '/marketing': typeof MarketingRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/whatsapp/automation': typeof WhatsappAutomationRoute
  '/whatsapp/campaigns': typeof WhatsappCampaignsRoute
  '/whatsapp/logs': typeof WhatsappLogsRoute
  '/whatsapp/templates': typeof WhatsappTemplatesRoute
  '/whatsapp/': typeof WhatsappIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/clients': typeof ClientsRoute
  '/inventory': typeof InventoryRoute
  '/marketing': typeof MarketingRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/whatsapp/automation': typeof WhatsappAutomationRoute
  '/whatsapp/campaigns': typeof WhatsappCampaignsRoute
  '/whatsapp/logs': typeof WhatsappLogsRoute
  '/whatsapp/templates': typeof WhatsappTemplatesRoute
  '/whatsapp': typeof WhatsappIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/clients': typeof ClientsRoute
  '/inventory': typeof InventoryRoute
  '/marketing': typeof MarketingRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/whatsapp/automation': typeof WhatsappAutomationRoute
  '/whatsapp/campaigns': typeof WhatsappCampaignsRoute
  '/whatsapp/logs': typeof WhatsappLogsRoute
  '/whatsapp/templates': typeof WhatsappTemplatesRoute
  '/whatsapp/': typeof WhatsappIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/clients'
    | '/inventory'
    | '/marketing'
    | '/payments'
    | '/reports'
    | '/services'
    | '/settings'
    | '/whatsapp/automation'
    | '/whatsapp/campaigns'
    | '/whatsapp/logs'
    | '/whatsapp/templates'
    | '/whatsapp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/clients'
    | '/inventory'
    | '/marketing'
    | '/payments'
    | '/reports'
    | '/services'
    | '/settings'
    | '/whatsapp/automation'
    | '/whatsapp/campaigns'
    | '/whatsapp/logs'
    | '/whatsapp/templates'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/clients'
    | '/inventory'
    | '/marketing'
    | '/payments'
    | '/reports'
    | '/services'
    | '/settings'
    | '/whatsapp/automation'
    | '/whatsapp/campaigns'
    | '/whatsapp/logs'
    | '/whatsapp/templates'
    | '/whatsapp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ClientsRoute: typeof ClientsRoute
  InventoryRoute: typeof InventoryRoute
  MarketingRoute: typeof MarketingRoute
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  WhatsappAutomationRoute: typeof WhatsappAutomationRoute
  WhatsappCampaignsRoute: typeof WhatsappCampaignsRoute
  WhatsappLogsRoute: typeof WhatsappLogsRoute
  WhatsappTemplatesRoute: typeof WhatsappTemplatesRoute
  WhatsappIndexRoute: typeof WhatsappIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/': {
      id: '/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof WhatsappIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/templates': {
      id: '/whatsapp/templates'
      path: '/whatsapp/templates'
      fullPath: '/whatsapp/templates'
      preLoaderRoute: typeof WhatsappTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/logs': {
      id: '/whatsapp/logs'
      path: '/whatsapp/logs'
      fullPath: '/whatsapp/logs'
      preLoaderRoute: typeof WhatsappLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/campaigns': {
      id: '/whatsapp/campaigns'
      path: '/whatsapp/campaigns'
      fullPath: '/whatsapp/campaigns'
      preLoaderRoute: typeof WhatsappCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/automation': {
      id: '/whatsapp/automation'
      path: '/whatsapp/automation'
      fullPath: '/whatsapp/automation'
      preLoaderRoute: typeof WhatsappAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  ClientsRoute: ClientsRoute,
  InventoryRoute: InventoryRoute,
  MarketingRoute: MarketingRoute,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  WhatsappAutomationRoute: WhatsappAutomationRoute,
  WhatsappCampaignsRoute: WhatsappCampaignsRoute,
  WhatsappLogsRoute: WhatsappLogsRoute,
  WhatsappTemplatesRoute: WhatsappTemplatesRoute,
  WhatsappIndexRoute: WhatsappIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
